"""add concept progress tracking

Revision ID: 3735524241fb
Revises: b0ab6f135418
Create Date: 2026-09-14 09:14:42.844033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3735524241fb'
down_revision: Union[str, Sequence[str], None] = 'b0ab6f135418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.String(length=50), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_progress_document_id'), 'concept_progress', ['document_id'], unique=False)
    op.create_index(op.f('ix_concept_progress_project_id'), 'concept_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_concept_progress_topic'), 'concept_progress', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_progress_topic'), table_name='concept_progress')
    op.drop_index(op.f('ix_concept_progress_project_id'), table_name='concept_progress')
    op.drop_index(op.f('ix_concept_progress_document_id'), table_name='concept_progress')
    op.drop_table('concept_progress')
    # ### end Alembic commands ###
