"""add study challenges and attempts

Revision ID: b0ab6f135418
Revises: 4bf9defda82d
Create Date: 2026-09-13 15:13:12.398110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ab6f135418'
down_revision: Union[str, Sequence[str], None] = '4bf9defda82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_challenges_document_id'), 'study_challenges', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_challenges_project_id'), 'study_challenges', ['project_id'], unique=False)
    op.create_table('challenge_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('missing_points', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['study_challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_attempts_challenge_id'), 'challenge_attempts', ['challenge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_attempts_challenge_id'), table_name='challenge_attempts')
    op.drop_table('challenge_attempts')
    op.drop_index(op.f('ix_study_challenges_project_id'), table_name='study_challenges')
    op.drop_index(op.f('ix_study_challenges_document_id'), table_name='study_challenges')
    op.drop_table('study_challenges')
    # ### end Alembic commands ###
