"""add concept to study challenges

Revision ID: bcc1386ebb00
Revises: 3735524241fb
Create Date: 2026-09-15 19:32:17.233356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1386ebb00'
down_revision: Union[str, Sequence[str], None] = '3735524241fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_challenges', sa.Column('concept', sa.String(length=255), nullable=True))
    op.execute("UPDATE study_challenges SET concept = 'legacy' WHERE concept IS NULL")
    op.alter_column('study_challenges', 'concept', nullable=False)
    op.create_index(op.f('ix_study_challenges_concept'), 'study_challenges', ['concept'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_challenges_concept'), table_name='study_challenges')
    op.drop_column('study_challenges', 'concept')
    # ### end Alembic commands ###
