"""add canonical knowledge gap registry

Revision ID: ccdf96f90daf
Revises: e3b75e0c67c1
Create Date: 2026-09-23 05:52:01.676239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdf96f90daf'
down_revision: Union[str, Sequence[str], None] = 'e3b75e0c67c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('gap_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_id', 'concept', 'gap_key', name='uq_knowledge_gap_scope_concept_key')
    )
    op.create_index(op.f('ix_knowledge_gaps_concept'), 'knowledge_gaps', ['concept'], unique=False)
    op.create_index(op.f('ix_knowledge_gaps_document_id'), 'knowledge_gaps', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_gaps_project_id'), 'knowledge_gaps', ['project_id'], unique=False)
    op.create_table('challenge_attempt_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_gap_id', sa.UUID(), nullable=False),
    sa.Column('raw_missing_point', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['challenge_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_gap_id'], ['knowledge_gaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'knowledge_gap_id', 'raw_missing_point', name='uq_attempt_gap_raw_point')
    )
    op.create_index(op.f('ix_challenge_attempt_gaps_attempt_id'), 'challenge_attempt_gaps', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_challenge_attempt_gaps_knowledge_gap_id'), 'challenge_attempt_gaps', ['knowledge_gap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_attempt_gaps_knowledge_gap_id'), table_name='challenge_attempt_gaps')
    op.drop_index(op.f('ix_challenge_attempt_gaps_attempt_id'), table_name='challenge_attempt_gaps')
    op.drop_table('challenge_attempt_gaps')
    op.drop_index(op.f('ix_knowledge_gaps_project_id'), table_name='knowledge_gaps')
    op.drop_index(op.f('ix_knowledge_gaps_document_id'), table_name='knowledge_gaps')
    op.drop_index(op.f('ix_knowledge_gaps_concept'), table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    # ### end Alembic commands ###
