"""add next review scheduling

Revision ID: e3b75e0c67c1
Revises: f5ca6b7292e2
Create Date: 2026-09-18 05:03:43.985980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b75e0c67c1'
down_revision: Union[str, Sequence[str], None] = 'f5ca6b7292e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_progress', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_progress', 'next_review_at')
    # ### end Alembic commands ###
