"""add concept to concept progress

Revision ID: f5ca6b7292e2
Revises: 1070bd679ab8
Create Date: 2026-09-15 20:27:05.212001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ca6b7292e2'
down_revision: Union[str, Sequence[str], None] = '1070bd679ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_progress', sa.Column('concept', sa.String(length=255), nullable=True))
    op.execute("UPDATE concept_progress SET concept = 'legacy' WHERE concept IS NULL")
    op.alter_column('concept_progress', 'concept', nullable=False)
    op.create_index(op.f('ix_concept_progress_concept'), 'concept_progress', ['concept'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_progress_concept'), table_name='concept_progress')
    op.drop_column('concept_progress', 'concept')
    # ### end Alembic commands ###
